# Generated by Django 4.0.5 on 2022-06-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_resume_collegename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='firstName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='lastName',
        ),
    ]
